### ISSUE TITLE
I upgraded the project to nullsafety

### ISSUE THREAD

**Issue by moham96** [eclipseglory/torrent_task#7]
Hi, @eclipseglory 
I have migrated the project(with all its dependencies) to null safety.
If I make PRs to your repos will you merge my commits and release the packages (which I would prefer) or should I hard fork your packages?

Regards

**Comment by cbenhagen** [comment]
Thanks for working on this! Please just go ahead and open a pull request for visibility.

**Comment by moham96** [comment]
> Thanks for working on this! Please just go ahead and open a pull request for visibility.

Well the problem is I'm not sure how to go about this regarding the `pubspec.yaml` dependencies
my local repos currently have all dependencies using `path` instead of a version from `pub.dev`, something like this:

```
dependencies:
  torrent_model:
    path: ../torrent_model
  torrent_tracker:
    path: ../torrent_tracker
  dht_dart:
    path: ../dht
  dartorrent_common:
    path: ../dartorrent_common
  bencode_dart:
    path: ../bencode_dart
  utp:
    path: ../utp
```
which I don't think I should push like this, it should instead have a version number, so ideally I would push changes to the dependencies repos like `dht` and `utp` with a version bump, and then use these versions in the `pubspec.yaml` in the dependant packages before pushing
